package gearmanij;

public interface Constants {
	/* Defines. */
	public static final String GEARMAN_DEFAULT_TCP_HOST = "127.0.0.1";
	public static final int GEARMAN_DEFAULT_TCP_PORT = 4730;
	public static final int GEARMAN_DEFAULT_SOCKET_TIMEOUT = 10;
	public static final int GEARMAN_DEFAULT_SOCKET_SEND_SIZE = 32768;
	public static final int GEARMAN_DEFAULT_SOCKET_RECV_SIZE = 32768;
	public static final int GEARMAN_DEFAULT_BACKLOG = 64;
	public static final int GEARMAN_DEFAULT_MAX_QUEUE_SIZE = 0;

	public static final int GEARMAN_MAX_ERROR_SIZE = 1024;
	public static final int GEARMAN_PACKET_HEADER_SIZE = 12;
	public static final int GEARMAN_JOB_HANDLE_SIZE = 64;
	public static final int GEARMAN_OPTION_SIZE = 64;
	public static final int GEARMAN_UNIQUE_SIZE = 64;
	public static final int GEARMAN_MAX_COMMAND_ARGS = 8;
	public static final int GEARMAN_ARGS_BUFFER_SIZE = 128;
	public static final int GEARMAN_SEND_BUFFER_SIZE = 8192;
	public static final int GEARMAN_RECV_BUFFER_SIZE = 8192;
	public static final int GEARMAN_SERVER_CON_ID_SIZE = 128;
	public static final int GEARMAN_JOB_HASH_SIZE = 383;
	public static final int GEARMAN_MAX_FREE_SERVER_CON = 1000;
	public static final int GEARMAN_MAX_FREE_SERVER_PACKET = 2000;
	public static final int GEARMAN_MAX_FREE_SERVER_JOB = 1000;
	public static final int GEARMAN_MAX_FREE_SERVER_CLIENT = 1000;
	public static final int GEARMAN_MAX_FREE_SERVER_WORKER = 1000;
	public static final int GEARMAN_TEXT_RESPONSE_SIZE = 8192;
	public static final int GEARMAN_WORKER_WAIT_TIMEOUT = (10 * 1000); /* Milliseconds */
	public static final int GEARMAN_PIPE_BUFFER_SIZE = 256;

	enum GEARMAN_RETURN_CODES
	{
	  GEARMAN_SUCCESS,
	  GEARMAN_IO_WAIT,
	  GEARMAN_SHUTDOWN,
	  GEARMAN_SHUTDOWN_GRACEFUL,
	  GEARMAN_ERRNO,
	  GEARMAN_EVENT,
	  GEARMAN_TOO_MANY_ARGS,
	  GEARMAN_NO_ACTIVE_FDS,
	  GEARMAN_INVALID_MAGIC,
	  GEARMAN_INVALID_COMMAND,
	  GEARMAN_INVALID_PACKET,
	  GEARMAN_UNEXPECTED_PACKET,
	  GEARMAN_GETADDRINFO,
	  GEARMAN_NO_SERVERS,
	  GEARMAN_LOST_CONNECTION,
	  GEARMAN_MEMORY_ALLOCATION_FAILURE,
	  GEARMAN_JOB_EXISTS,
	  GEARMAN_JOB_QUEUE_FULL,
	  GEARMAN_SERVER_ERROR,
	  GEARMAN_WORK_ERROR,
	  GEARMAN_WORK_DATA,
	  GEARMAN_WORK_WARNING,
	  GEARMAN_WORK_STATUS,
	  GEARMAN_WORK_EXCEPTION,
	  GEARMAN_WORK_FAIL,
	  GEARMAN_NOT_CONNECTED,
	  GEARMAN_COULD_NOT_CONNECT,
	  GEARMAN_SEND_IN_PROGRESS,
	  GEARMAN_RECV_IN_PROGRESS,
	  GEARMAN_NOT_FLUSHING,
	  GEARMAN_DATA_TOO_LARGE,
	  GEARMAN_INVALID_FUNCTION_NAME,
	  GEARMAN_INVALID_WORKER_FUNCTION,
	  GEARMAN_NO_REGISTERED_FUNCTIONS,
	  GEARMAN_NO_JOBS,
	  GEARMAN_ECHO_DATA_CORRUPTION,
	  GEARMAN_NEED_WORKLOAD_FN,
	  GEARMAN_PAUSE,
	  GEARMAN_UNKNOWN_STATE,
	  GEARMAN_PTHREAD,
	  GEARMAN_PIPE_EOF,
	  GEARMAN_MAX_RETURN /* Always add new error code before */
	};

}
